[package]
name = "alloy-kernel-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[features]
default = ["i686"]
i686 = ["alloy-kernel-hal/i686"]
x86_64 = ["alloy-kernel-hal/x86_64"]
aarch64 = ["alloy-kernel-hal/aarch64"]
debug-alloc = []

[dependencies]
alloy-display-kernel = { path = "../../Alloy-DE/alloy-display-kernel" }
alloy-kernel-hal = { path = "../hal" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 2
